// Demo listing data - representative but fictional Oahu listings.
// All prices, fees, and MLS numbers are sample data for the prototype.

const REGIONS = [
  { id: "metro", name: "Metro Honolulu", blurb: "Urban core: Waikiki, Ala Moana, Kakaako, Makiki, Punchbowl. Condo-heavy, most of the island's leasehold inventory." },
  { id: "diamondhead", name: "Diamond Head / Kahala", blurb: "Gold coast estates and Kahala's flat, walkable luxury blocks makai of the crater." },
  { id: "hawaiikai", name: "Hawaii Kai", blurb: "Marina-front living in East Honolulu. Boat docks, Koko Head views, master-planned." },
  { id: "windward", name: "Windward: Kailua / Kaneohe", blurb: "Lush, wetter side under the Ko'olau. Beach-town Kailua, bay-side Kaneohe, many CPR homes." },
  { id: "northshore", name: "North Shore", blurb: "Haleiwa to Kahuku. Country by choice, big surf in winter, tsunami-zone awareness on the beach lots." },
  { id: "central", name: "Central: Mililani / Wahiawa", blurb: "Cooler elevation, planned communities, strong owner-occupant townhome market." },
  { id: "pearlcity", name: "Pearl City / Aiea", blurb: "Mid-island value with Pearl Harbor views and quick H-1/H-2 access." },
  { id: "ewa", name: "Ewa Plain", blurb: "Newest single-family inventory on the island. Sunny, dry, and PV-friendly rooflines." },
  { id: "kapolei", name: "Kapolei / Makakilo", blurb: "The 'second city'. New construction, rail access, Makakilo's uphill trade winds." },
  { id: "leeward", name: "Leeward Coast", blurb: "Nanakuli to Makaha. The island's most attainable oceanfront, plus DHHL homestead communities." },
];

const MAINT_LABELS = {
  electricity: "Electricity", water: "Water", hotwater: "Hot water", sewer: "Sewer",
  cable: "Cable/internet", insurance: "Bldg. insurance", gas: "Gas",
};

const LISTINGS = [
  {
    id: "l01", mls: "D-2607114", address: "2345 Ala Wai Blvd #1204", neighborhood: "Waikiki",
    region: "metro", price: 299000, beds: 2, baths: 1, sqft: 780, lanaiSqft: 96, parking: 1,
    type: "condo", tenure: "LH", yearBuilt: 1974,
    lease: { rentMonthly: 611, expYear: 2043, renegYear: 2033, lessor: "Queen Emma Land Co.", feeAvailable: false, feePrice: null },
    maintFee: 587, maintIncludes: ["electricity", "water", "hotwater", "sewer", "cable"],
    taxAssessed: 465000, floodZone: "X", tsunamiEvac: true, slrExposure: false, sewer: "sewer",
    pv: "none", strEligible: false, views: ["Ala Wai Canal", "Ko'olau"], orientation: "mauka",
    imgSeed: "waikiki-alawai-condo-tower",
    desc: "Classic Waikiki leasehold value. Corner 2BR with canal and mountain views, one block mauka of the beach. Lease rent fixed until the 2033 renegotiation.",
  },
  {
    id: "l02", mls: "D-2606882", address: "1425 Punahou St #805", neighborhood: "Makiki",
    region: "metro", price: 265000, beds: 2, baths: 2, sqft: 842, lanaiSqft: 60, parking: 1,
    type: "condo", tenure: "LH", yearBuilt: 1969,
    lease: { rentMonthly: 434, expYear: 2039, renegYear: 2029, lessor: "Private trust", feeAvailable: true, feePrice: 182000 },
    maintFee: 712, maintIncludes: ["electricity", "water", "hotwater", "sewer", "cable"],
    taxAssessed: 410000, floodZone: "X", tsunamiEvac: false, slrExposure: false, sewer: "sewer",
    pv: "none", strEligible: false, views: ["City", "Diamond Head"], orientation: "makai",
    imgSeed: "makiki-punahou-highrise",
    desc: "Fee available: buy the leased fee for $182k and convert to fee simple. Wide makai lanai with Diamond Head framing, walkable Makiki location.",
  },
  {
    id: "l03", mls: "D-2607501", address: "988 Halekauwila St #2710", neighborhood: "Kakaako",
    region: "metro", price: 1150000, beds: 2, baths: 2, sqft: 1046, lanaiSqft: 0, parking: 2,
    type: "condo", tenure: "FS", yearBuilt: 2019,
    lease: null,
    maintFee: 1084, maintIncludes: ["water", "hotwater", "sewer", "cable", "insurance"],
    taxAssessed: 1120000, floodZone: "X", tsunamiEvac: true, slrExposure: true, sewer: "sewer",
    pv: "none", strEligible: false, views: ["Ocean", "Harbor"], orientation: "makai",
    imgSeed: "kakaako-glass-tower-unit",
    desc: "Newer Kakaako tower with resort amenities. Assessed in the Residential A tier if not owner-occupied; run both tax scenarios in the cost panel.",
  },
  {
    id: "l04", mls: "D-2606240", address: "520 Lunalilo Home Rd", neighborhood: "Hawaii Kai",
    region: "hawaiikai", price: 1595000, beds: 4, baths: 3, sqft: 2210, lanaiSqft: 340, parking: 2,
    type: "single", tenure: "FS", yearBuilt: 1988,
    lease: null,
    maintFee: 0, maintIncludes: [], hoaFee: 68,
    taxAssessed: 1480000, floodZone: "AE", tsunamiEvac: true, slrExposure: true, sewer: "sewer",
    pv: "owned-nem", strEligible: false, views: ["Marina", "Koko Head"], orientation: "makai",
    imgSeed: "hawaii-kai-marina-home",
    desc: "Marina-front with private dock. Owned PV on a grandfathered NEM agreement that transfers with sale.",
  },
  {
    id: "l05", mls: "D-2607333", address: "231 Kuulei Rd", neighborhood: "Kailua",
    region: "windward", price: 1850000, beds: 3, baths: 2, sqft: 1560, lanaiSqft: 220, parking: 2,
    type: "single", tenure: "FS", yearBuilt: 1957,
    lease: null,
    maintFee: 0, maintIncludes: [],
    taxAssessed: 1720000, floodZone: "X", tsunamiEvac: false, slrExposure: false, sewer: "sewer",
    pv: "none", strEligible: false, views: ["Garden", "Ko'olau"], orientation: "mauka",
    imgSeed: "kailua-beach-cottage-yard",
    desc: "Single-level Kuulei Tract classic, five minutes' bike to Kailua Beach. Level lot with room for an ohana unit (verify with DPP).",
  },
  {
    id: "l06", mls: "D-2605998", address: "95-1055 Ainamakua Dr #12", neighborhood: "Mililani Mauka",
    region: "central", price: 720000, beds: 3, baths: 2.5, sqft: 1188, lanaiSqft: 40, parking: 2,
    type: "town", tenure: "FS", yearBuilt: 2002,
    lease: null,
    maintFee: 428, maintIncludes: ["water", "sewer", "insurance"], hoaFee: 46,
    taxAssessed: 690000, floodZone: "X", tsunamiEvac: false, slrExposure: false, sewer: "sewer",
    pv: "none", strEligible: false, views: ["Garden"], orientation: "mauka",
    imgSeed: "mililani-townhome-row",
    desc: "Mililani Mauka townhome at cooler elevation with trade-wind flow. Association covers water, sewer, and building insurance.",
  },
  {
    id: "l07", mls: "D-2607420", address: "91-1170 Kaileolea Dr", neighborhood: "Ocean Pointe",
    region: "ewa", price: 892000, beds: 4, baths: 2.5, sqft: 1710, lanaiSqft: 120, parking: 2,
    type: "single", tenure: "FS", yearBuilt: 2014,
    lease: null,
    maintFee: 0, maintIncludes: [], hoaFee: 112,
    taxAssessed: 858000, floodZone: "D", tsunamiEvac: false, slrExposure: false, sewer: "sewer",
    pv: "owned-nem", strEligible: false, views: ["Garden"], orientation: "makai",
    imgSeed: "ewa-beach-new-single-family",
    desc: "Newer Ewa Plain single-family with owned PV + battery on the island's sunniest coast. HOA covers common areas and parks.",
  },
  {
    id: "l08", mls: "D-2606671", address: "45-408 Nakuluai St", neighborhood: "Kaneohe",
    region: "windward", price: 1050000, beds: 3, baths: 2, sqft: 1320, lanaiSqft: 180, parking: 2,
    type: "cpr", tenure: "FS", yearBuilt: 1978,
    lease: null,
    maintFee: 0, maintIncludes: [],
    taxAssessed: 990000, floodZone: "X", tsunamiEvac: false, slrExposure: false, sewer: "cesspool",
    pv: "leased", strEligible: false, views: ["Ko'olau", "Kaneohe Bay"], orientation: "mauka",
    imgSeed: "kaneohe-hillside-home-koolau",
    desc: "Detached home held as a CPR (two homes share one lot; no maintenance fee, shared driveway agreement). On a cesspool: factor the pre-2050 conversion.",
  },
  {
    id: "l09", mls: "D-2605430", address: "87-1902 Pakeke St", neighborhood: "Maili",
    region: "leeward", price: 425000, beds: 3, baths: 2, sqft: 1120, lanaiSqft: 0, parking: 2,
    type: "single", tenure: "DHHL", yearBuilt: 1996,
    lease: { rentMonthly: 0, expYear: 2095, renegYear: null, lessor: "Dept. of Hawaiian Home Lands", feeAvailable: false, feePrice: null },
    maintFee: 0, maintIncludes: [],
    taxAssessed: 402000, floodZone: "X", tsunamiEvac: false, slrExposure: false, sewer: "sewer",
    pv: "owned-nem", strEligible: false, views: ["Ocean"], orientation: "makai",
    imgSeed: "waianae-coast-homestead",
    desc: "Hawaiian Home Lands homestead. Buyer must be a DHHL beneficiary (50% or greater Native Hawaiian ancestry). 99-year lease at $1/year.",
  },
  {
    id: "l10", mls: "D-2607219", address: "59-420 Ke Nui Rd", neighborhood: "Sunset Beach",
    region: "northshore", price: 1395000, beds: 2, baths: 1, sqft: 864, lanaiSqft: 260, parking: 3,
    type: "single", tenure: "FS", yearBuilt: 1962,
    lease: null,
    maintFee: 0, maintIncludes: [],
    taxAssessed: 1310000, floodZone: "VE", tsunamiEvac: true, slrExposure: true, sewer: "cesspool",
    pv: "none", strEligible: false, views: ["Ocean", "Sunset"], orientation: "makai",
    imgSeed: "north-shore-beach-cottage",
    desc: "Beachfront cottage steps from Sunset's sand. Coastal flood zone, tsunami evacuation area, and cesspool: priced for buyers who know the coast.",
  },
  {
    id: "l11", mls: "D-2604815", address: "3045 Ala Napunani St #506", neighborhood: "Salt Lake",
    region: "metro", price: 168000, beds: 1, baths: 1, sqft: 560, lanaiSqft: 48, parking: 1,
    type: "condo", tenure: "LH", yearBuilt: 1971,
    lease: { rentMonthly: 389, expYear: 2031, renegYear: null, lessor: "Private trust", feeAvailable: false, feePrice: null },
    maintFee: 498, maintIncludes: ["electricity", "water", "hotwater", "sewer"],
    taxAssessed: 255000, floodZone: "X", tsunamiEvac: false, slrExposure: false, sewer: "sewer",
    pv: "none", strEligible: false, views: ["City"], orientation: "mauka",
    imgSeed: "salt-lake-condo-building",
    desc: "Short-lease pricing: 5 years remain, cash buyers only. A clear example of why lease years drive leasehold value more than square footage.",
  },
  {
    id: "l12", mls: "D-2607177", address: "2427 Kuhio Ave #1808", neighborhood: "Waikiki",
    region: "metro", price: 525000, beds: 1, baths: 1, sqft: 533, lanaiSqft: 64, parking: 0,
    type: "condo", tenure: "FS", yearBuilt: 1979,
    lease: null,
    maintFee: 902, maintIncludes: ["electricity", "water", "hotwater", "sewer", "cable", "insurance"],
    taxAssessed: 498000, floodZone: "X", tsunamiEvac: true, slrExposure: false, sewer: "sewer",
    pv: "none", strEligible: true, views: ["Ocean", "City"], orientation: "makai",
    imgSeed: "waikiki-condotel-resort-tower",
    desc: "Resort-zoned condotel: legal short-term rental under Bill 41 with hotel front desk in the building. Fee includes all utilities.",
  },
  {
    id: "l13", mls: "D-2606055", address: "4614 Kahala Ave", neighborhood: "Kahala",
    region: "diamondhead", price: 3900000, beds: 5, baths: 4.5, sqft: 3480, lanaiSqft: 520, parking: 3,
    type: "single", tenure: "FS", yearBuilt: 2005,
    lease: null,
    maintFee: 0, maintIncludes: [],
    taxAssessed: 3650000, floodZone: "X", tsunamiEvac: true, slrExposure: false, sewer: "sewer",
    pv: "owned-nem", strEligible: false, views: ["Ocean", "Diamond Head"], orientation: "makai",
    imgSeed: "kahala-avenue-estate",
    desc: "Kahala Avenue address one lot off the sand. Pool pavilion, owned PV, and a flat walk to Kahala Beach. Residential A tax tier if not owner-occupied.",
  },
  {
    id: "l14", mls: "D-2605764", address: "98-402 Koauka Loop #A21", neighborhood: "Pearlridge",
    region: "pearlcity", price: 640000, beds: 3, baths: 2, sqft: 1108, lanaiSqft: 72, parking: 2,
    type: "town", tenure: "FS", yearBuilt: 1990,
    lease: null,
    maintFee: 516, maintIncludes: ["water", "sewer", "cable", "insurance"],
    taxAssessed: 612000, floodZone: "X", tsunamiEvac: false, slrExposure: false, sewer: "sewer",
    pv: "none", strEligible: false, views: ["Pearl Harbor", "City"], orientation: "makai",
    imgSeed: "aiea-pearlridge-townhome",
    desc: "Three-bedroom townhome above Pearlridge with harbor views and central access to both H-1 and H-2.",
  },
  {
    id: "l15", mls: "D-2607048", address: "820 W Hind Dr", neighborhood: "Aina Haina",
    region: "diamondhead", price: 1450000, beds: 3, baths: 2, sqft: 1680, lanaiSqft: 150, parking: 2,
    type: "single", tenure: "FS", yearBuilt: 1965,
    lease: null,
    maintFee: 0, maintIncludes: [],
    taxAssessed: 1380000, floodZone: "X", tsunamiEvac: false, slrExposure: false, sewer: "sewer",
    pv: "leased", strEligible: false, views: ["Ocean", "Valley"], orientation: "mauka",
    imgSeed: "aina-haina-valley-home",
    desc: "Aina Haina valley home with ocean glimpses from the lanai. PV is leased: review the transfer terms before closing.",
  },
  {
    id: "l16", mls: "D-2607392", address: "92-1001 Aliinui Dr #14B", neighborhood: "Ko Olina",
    region: "kapolei", price: 815000, beds: 2, baths: 2, sqft: 980, lanaiSqft: 110, parking: 2,
    type: "condo", tenure: "FS", yearBuilt: 2003,
    lease: null,
    maintFee: 894, maintIncludes: ["water", "hotwater", "sewer", "cable", "insurance"],
    taxAssessed: 792000, floodZone: "X", tsunamiEvac: true, slrExposure: false, sewer: "sewer",
    pv: "none", strEligible: true, views: ["Golf", "Sunset"], orientation: "makai",
    imgSeed: "ko-olina-resort-condo",
    desc: "Ko Olina resort-zone condo: STR-legal, lagoon access, sunset golf views. Popular with mainland buyers running both tax tiers.",
  },
  {
    id: "l17", mls: "D-2606518", address: "1519 Nuuanu Ave #942", neighborhood: "Nuuanu / Punchbowl",
    region: "metro", price: 355000, beds: 2, baths: 1, sqft: 726, lanaiSqft: 0, parking: 1,
    type: "condo", tenure: "LH", yearBuilt: 1975,
    lease: { rentMonthly: 288, expYear: 2054, renegYear: 2034, lessor: "Kamehameha Schools", feeAvailable: true, feePrice: 145000 },
    maintFee: 604, maintIncludes: ["water", "hotwater", "sewer", "cable"],
    taxAssessed: 388000, floodZone: "X", tsunamiEvac: false, slrExposure: false, sewer: "sewer",
    pv: "none", strEligible: false, views: ["City", "Harbor"], orientation: "makai",
    imgSeed: "nuuanu-punchbowl-condo",
    desc: "Long lease (29 years) with the fee available from Kamehameha Schools. Financeable today; buying the fee pencils out against the rent step-up.",
  },
  {
    id: "l18", mls: "D-2607255", address: "2728 S King St #301", neighborhood: "Moiliili",
    region: "metro", price: 455000, beds: 2, baths: 1, sqft: 690, lanaiSqft: 55, parking: 1,
    type: "condo", tenure: "FS", yearBuilt: 1981,
    lease: null,
    maintFee: 548, maintIncludes: ["water", "hotwater", "sewer"],
    taxAssessed: 438000, floodZone: "AE", tsunamiEvac: false, slrExposure: false, sewer: "sewer",
    pv: "none", strEligible: false, views: ["City"], orientation: "mauka",
    imgSeed: "moiliili-king-street-condo",
    desc: "Fee-simple walk-to-UH two-bedroom on the King Street corridor, an easy bus or bike to campus and Ala Moana.",
  },
];
