import Anthropic from "@anthropic-ai/sdk";
import { MaturityLevel, LevelRelation, Tutorial } from "@/types";

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY!,
});

/** Strip markdown code fences from Claude's response before JSON.parse */
function parseJSON<T>(text: string): T {
  // Remove ```json ... ``` or ``` ... ``` wrappers
  const stripped = text.replace(/^```(?:json)?\s*\n?/i, "").replace(/\n?```\s*$/i, "");
  return JSON.parse(stripped) as T;
}

/** Classification result from the AI level classifier */
interface ClassificationResult {
  maturity_level: MaturityLevel;
  level_relation: LevelRelation;
  topics: string[];
  tags: string[];
  tools_mentioned: string[];
  difficulty: "beginner" | "intermediate" | "advanced";
}

/** Full tutorial generated by the AI pipeline */
interface GeneratedTutorial {
  title: string;
  slug: string;
  summary: string;
  body: string;
  action_items: string[];
  classification: ClassificationResult;
}

const LEVEL_CLASSIFIER_PROMPT = `You are an AI content classifier for Battle Cat AI, a learning platform built around the AI Maturity Framework.

Classify the following content into the framework:

LEVELS:
- L0 (Asker → Answerer): Basic AI usage, one-off questions, no context. Tools: ChatGPT, Claude, Gemini.
- L1 (Instructor → Assistant): Personalization, memory, custom instructions, context investment. Tools: Custom GPTs, Projects, Gems.
- L2 (Designer → Builder): Vibe coding, describe-and-build, rapid prototyping. Tools: Lovable, v0, Bolt, Replit.
- L3 (Supervisor → Agent): Agentic coding, autonomous AI, define "done" and walk away. Tools: Claude Code, Cursor, Devin.
- L4 (Architect → Organization): Multi-agent orchestration, agent swarming, system design. Tools: Multi-agent frameworks, parallel execution.

LEVEL RELATIONS:
- "level-up": Teaches how to move FROM this level to the next level
- "level-practice": Deepens skills AT this level
- "cross-level": Spans multiple levels

Respond ONLY with valid JSON matching this schema:
{
  "maturity_level": <0|1|2|3|4>,
  "level_relation": "<level-up|level-practice|cross-level>",
  "topics": ["<topic1>", "<topic2>"],
  "tags": ["<tag1>", "<tag2>"],
  "tools_mentioned": ["<tool1>"],
  "difficulty": "<beginner|intermediate|advanced>"
}`;

const TUTORIAL_GENERATOR_PROMPT = `You are a tutorial writer for Battle Cat AI, a learning platform that organizes AI knowledge by maturity level.

Transform the following extracted content into a polished, step-by-step tutorial blog post. The tutorial should:

1. Have a clear, compelling title
2. Start with a 2-3 sentence summary
3. Be written in a confident but approachable tone — like a smart friend sharing notes
4. Include numbered step-by-step instructions where applicable
5. End with 2-5 concrete "Try This" action items the reader can do right now
6. Reference specific tools by name when relevant

Generate a URL-friendly slug from the title (lowercase, hyphens, no special characters).

Respond ONLY with valid JSON matching this schema:
{
  "title": "<string>",
  "slug": "<url-slug>",
  "summary": "<2-3 sentences>",
  "body": "<full markdown tutorial body>",
  "action_items": ["<action1>", "<action2>"]
}`;

/**
 * Classify content into the AI Maturity Framework.
 */
export async function classifyContent(
  rawText: string,
): Promise<ClassificationResult> {
  const message = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 1024,
    messages: [
      {
        role: "user",
        content: `${LEVEL_CLASSIFIER_PROMPT}\n\n---\n\nCONTENT TO CLASSIFY:\n${rawText.slice(0, 8000)}`,
      },
    ],
  });

  const text =
    message.content[0].type === "text" ? message.content[0].text : "";
  return parseJSON<ClassificationResult>(text);
}

/**
 * Generate a full tutorial from extracted content.
 */
export async function generateTutorial(
  rawText: string,
  sourceUrl: string,
): Promise<GeneratedTutorial> {
  // Step 1: Classify
  const classification = await classifyContent(rawText);

  // Step 2: Generate tutorial
  const message = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 4096,
    messages: [
      {
        role: "user",
        content: `${TUTORIAL_GENERATOR_PROMPT}\n\n---\n\nMATURITY LEVEL: L${classification.maturity_level}\nTOPICS: ${classification.topics.join(", ")}\nSOURCE URL: ${sourceUrl}\n\nEXTRACTED CONTENT:\n${rawText.slice(0, 12000)}`,
      },
    ],
  });

  const text =
    message.content[0].type === "text" ? message.content[0].text : "";
  const tutorial = parseJSON<Omit<GeneratedTutorial, "classification">>(text);

  return { ...tutorial, classification };
}

/**
 * Merge new content into an existing tutorial, making it richer.
 * The original sources are preserved as references.
 */
export async function mergeTutorial(
  existingTutorial: Tutorial,
  newRawText: string,
  newSourceUrl: string,
): Promise<{ body: string; summary: string; action_items: string[] }> {
  const message = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 4096,
    messages: [
      {
        role: "user",
        content: `You are merging new information into an existing tutorial on Battle Cat AI.

EXISTING TUTORIAL:
Title: ${existingTutorial.title}
Summary: ${existingTutorial.summary}
Body:
${existingTutorial.body}

NEW CONTENT (from ${newSourceUrl}):
${newRawText.slice(0, 8000)}

Merge the new information into the existing tutorial. Keep the same structure but enrich it with any new insights, steps, or examples. Do NOT duplicate information. The result should read as one cohesive tutorial, not two stitched together.

Respond ONLY with valid JSON:
{
  "body": "<updated full markdown body>",
  "summary": "<updated 2-3 sentence summary>",
  "action_items": ["<updated action items>"]
}`,
      },
    ],
  });

  const text =
    message.content[0].type === "text" ? message.content[0].text : "";
  return parseJSON(text);
}
