import Anthropic from "@anthropic-ai/sdk";
import { MaturityLevel, LevelRelation, Tutorial } from "@/types";

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY!,
});

/** Strip markdown code fences from Claude's response before JSON.parse */
function parseJSON<T>(text: string): T {
  // Remove ```json ... ``` or ``` ... ``` wrappers
  const stripped = text.replace(/^```(?:json)?\s*\n?/i, "").replace(/\n?```\s*$/i, "");
  return JSON.parse(stripped) as T;
}

/** Classification result from the AI level classifier */
interface ClassificationResult {
  maturity_level: MaturityLevel;
  level_relation: LevelRelation;
  topics: string[];
  tags: string[];
  tools_mentioned: string[];
  difficulty: "beginner" | "intermediate" | "advanced";
}

/** Full tutorial generated by the AI pipeline */
interface GeneratedTutorial {
  title: string;
  slug: string;
  summary: string;
  body: string;
  action_items: string[];
  classification: ClassificationResult;
}

const LEVEL_CLASSIFIER_PROMPT = `You are an AI content classifier for Battlecat AI, a learning platform built around the AI Maturity Framework.

Classify the following content into the framework:

LEVELS:
- L0 (Asker → Answerer): Basic AI usage, one-off questions, no context. Tools: ChatGPT, Claude, Gemini.
- L1 (Instructor → Assistant): Personalization, memory, custom instructions, context investment. Tools: Custom GPTs, Projects, Gems.
- L2 (Designer → Builder): Vibe coding, describe-and-build, rapid prototyping. Tools: Lovable, v0, Bolt, Replit.
- L3 (Supervisor → Agent): Agentic coding, autonomous AI, define "done" and walk away. Tools: Claude Code, Cursor, Devin.
- L4 (Architect → Organization): Multi-agent orchestration, agent swarming, system design. Tools: Multi-agent frameworks, parallel execution.

LEVEL RELATIONS:
- "level-up": Teaches how to move FROM this level to the next level
- "level-practice": Deepens skills AT this level
- "cross-level": Spans multiple levels

Respond ONLY with valid JSON matching this schema:
{
  "maturity_level": <0|1|2|3|4>,
  "level_relation": "<level-up|level-practice|cross-level>",
  "topics": ["<topic1>", "<topic2>"],
  "tags": ["<tag1>", "<tag2>"],
  "tools_mentioned": ["<tool1>"],
  "difficulty": "<beginner|intermediate|advanced>"
}`;

const TUTORIAL_GENERATOR_PROMPT = `You are a senior content writer for Battlecat AI, a premium learning platform that organizes AI knowledge by maturity level (L0 Asker through L4 Architect).

Transform the following extracted content into a beautifully structured, magazine-quality tutorial. This will be rendered on a polished blog — make it look and read like a top-tier tech publication (think Stratechery, Verge, or a well-produced Medium article).

WRITING GUIDELINES:
- Tone: Confident, direct, conversational. Like a smart friend sharing insights over coffee. Not academic, not hype-y.
- Use clear section headers (## and ###) to break content into scannable chunks
- Start with a compelling hook — not "In this tutorial" or "Let's explore"
- Use **bold** for key concepts and tool names when first introduced
- Use > blockquotes for key insights, memorable quotes, or "aha moment" takeaways
- Use bullet lists and numbered lists liberally for readability
- Include real examples and specific tool names — never be vague
- End each major section with a one-sentence takeaway
- Write 800-1500 words minimum — don't be thin. Flesh out ideas with examples, context, and practical detail.

STRUCTURE TEMPLATE (adapt as needed):
1. Opening hook (2-3 sentences that grab attention)
2. "Why This Matters" section — context and stakes
3. Core content sections (2-4 sections with ## headers)
4. Practical walkthrough or step-by-step where applicable
5. "The Bottom Line" — one-paragraph synthesis

FORMATTING RULES:
- Use ## for major sections, ### for subsections
- Use > blockquotes for key insights or takeaways (at least 2-3 per article)
- Use **bold** for emphasis (not ALL CAPS)
- Use \`inline code\` for tool names, commands, or technical terms
- Use --- between major sections for visual breathing room
- Use numbered lists for sequential steps, bullet lists for non-sequential items

Generate a URL-friendly slug from the title (lowercase, hyphens, no special characters, max 60 chars).

The summary should be a compelling 2-3 sentence hook that makes someone want to click and read the full tutorial. Not a dry description — sell the insight.

Respond ONLY with valid JSON matching this schema:
{
  "title": "<compelling, specific title — not generic>",
  "slug": "<url-slug>",
  "summary": "<2-3 sentence compelling hook>",
  "body": "<full markdown tutorial body, 800-1500+ words>",
  "action_items": ["<specific, actionable item with tool name>", "<another>"]
}`;

/**
 * Classify content into the AI Maturity Framework.
 */
export async function classifyContent(
  rawText: string,
): Promise<ClassificationResult> {
  const message = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 1024,
    messages: [
      {
        role: "user",
        content: `${LEVEL_CLASSIFIER_PROMPT}\n\n---\n\nCONTENT TO CLASSIFY:\n${rawText.slice(0, 8000)}`,
      },
    ],
  });

  const text =
    message.content[0].type === "text" ? message.content[0].text : "";
  return parseJSON<ClassificationResult>(text);
}

/**
 * Generate a full tutorial from extracted content.
 */
export async function generateTutorial(
  rawText: string,
  sourceUrl: string,
): Promise<GeneratedTutorial> {
  // Step 1: Classify
  const classification = await classifyContent(rawText);

  // Step 2: Generate tutorial
  const message = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 4096,
    messages: [
      {
        role: "user",
        content: `${TUTORIAL_GENERATOR_PROMPT}\n\n---\n\nMATURITY LEVEL: L${classification.maturity_level}\nTOPICS: ${classification.topics.join(", ")}\nSOURCE URL: ${sourceUrl}\n\nEXTRACTED CONTENT:\n${rawText.slice(0, 12000)}`,
      },
    ],
  });

  const text =
    message.content[0].type === "text" ? message.content[0].text : "";
  const tutorial = parseJSON<Omit<GeneratedTutorial, "classification">>(text);

  return { ...tutorial, classification };
}

/**
 * Merge new content into an existing tutorial, making it richer.
 * The original sources are preserved as references.
 */
export async function mergeTutorial(
  existingTutorial: Tutorial,
  newRawText: string,
  newSourceUrl: string,
): Promise<{ body: string; summary: string; action_items: string[] }> {
  const message = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 4096,
    messages: [
      {
        role: "user",
        content: `You are merging new information into an existing tutorial on Battlecat AI.

EXISTING TUTORIAL:
Title: ${existingTutorial.title}
Summary: ${existingTutorial.summary}
Body:
${existingTutorial.body}

NEW CONTENT (from ${newSourceUrl}):
${newRawText.slice(0, 8000)}

Merge the new information into the existing tutorial. Keep the same structure but enrich it with any new insights, steps, or examples. Do NOT duplicate information. The result should read as one cohesive tutorial, not two stitched together.

Respond ONLY with valid JSON:
{
  "body": "<updated full markdown body>",
  "summary": "<updated 2-3 sentence summary>",
  "action_items": ["<updated action items>"]
}`,
      },
    ],
  });

  const text =
    message.content[0].type === "text" ? message.content[0].text : "";
  return parseJSON(text);
}

/**
 * Generate a hot news headline and teaser for a tutorial flagged as hot news.
 * Returns a punchy, news-style headline and a 1-2 sentence teaser.
 */
export async function generateHotNewsBlurb(
  title: string,
  summary: string,
  toolsMentioned: string[],
): Promise<{ headline: string; teaser: string }> {
  const message = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 512,
    messages: [
      {
        role: "user",
        content: `Write a hot news headline and teaser for an AI news item.

TUTORIAL TITLE: ${title}
SUMMARY: ${summary}
TOOLS: ${toolsMentioned.join(", ")}

The headline should be punchy and specific — like a tech news headline (TechCrunch, The Verge style).
Focus on FUNCTIONALITY — what was launched, what it does, what's new. Not funding or hype.
The teaser should be 1-2 sentences that expand on the headline with the key capability or impact.

Respond ONLY with valid JSON:
{
  "headline": "<news-style headline, max 80 chars>",
  "teaser": "<1-2 sentence teaser, max 200 chars>"
}`,
      },
    ],
  });

  const text2 =
    message.content[0].type === "text" ? message.content[0].text : "";
  return parseJSON(text2);
}
